services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - DB_DRIVER=postgres
      - DATABASE_URL=postgres://authuser:authpass@postgres:5432/authdb?sslmode=disable

volumes:
  pgdata:
